(function () {
  "use strict";
  if (!window.LgndryAuth) return;
  var client = window.LgndryAuth.client;
  var main = document.querySelector("[data-account-main]");
  var state = { session: null, profile: null, orders: [] };

  function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (m) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m]; }); }
  function money(value) { return "R " + Number(value || 0).toLocaleString("en-ZA"); }
  function date(value, withTime) { if (!value) return "—"; var d = new Date(value); if (isNaN(d)) return value; return d.toLocaleString("en-ZA", withTime ? { dateStyle: "medium", timeStyle: "short" } : { dateStyle: "medium" }); }
  function firstItem(order) { var items = Array.isArray(order.items) ? order.items : []; return items[0] || {}; }
  function route() { var hash = location.hash.slice(1) || "orders"; if (hash.indexOf("order=") === 0) return { page: "order", id: hash.slice(6) }; return { page: ["profile", "orders", "tracking", "settings"].indexOf(hash) > -1 ? hash : "orders" }; }
  function heading(eyebrow, title, intro) { return '<header class="account-heading"><div><span class="account-eyebrow">' + esc(eyebrow) + '</span><h2>' + esc(title) + '</h2></div><p>' + esc(intro) + '</p></header>'; }
  function setActive(page) { document.querySelectorAll("[data-account-link]").forEach(function (link) { link.classList.toggle("is-active", link.dataset.accountLink === page); }); var mobile = document.querySelector("[data-mobile-account-nav]"); if (mobile && page !== "order") mobile.value = page; }

  function profileView() {
    var p = state.profile || {}; return heading("Personal details", "Profile", "Keep your delivery and contact details current for future order requests.") + '<form class="account-panel" action="https://www.lgndry-co.co.za/account.html" method="post" autocomplete="on" data-profile-form><div class="account-grid"><label class="auth-field"><span>Full name</span><input name="full_name" autocomplete="name" value="' + esc(p.full_name || state.session.user.user_metadata.full_name || "") + '" required></label><label class="auth-field"><span>Email</span><input value="' + esc(state.session.user.email || "") + '" disabled></label><label class="auth-field"><span>Phone</span><input name="phone" type="tel" autocomplete="tel" value="' + esc(p.phone || "") + '"></label><label class="auth-field"><span>City / town</span><input name="city" autocomplete="address-level2" value="' + esc(p.city || "") + '"></label><label class="auth-field auth-field--wide"><span>Delivery address</span><textarea name="address" autocomplete="street-address">' + esc(p.address || "") + '</textarea></label><label class="auth-field"><span>Postal code</span><input name="postal_code" autocomplete="postal-code" value="' + esc(p.postal_code || "") + '"></label></div><div class="account-savebar"><p class="auth-feedback" data-profile-feedback></p><button class="auth-button" type="submit">Save Profile</button></div></form>';
  }

  function orderCard(order) { var item = firstItem(order); return '<article class="order-card"><img class="order-card__image" src="' + esc(item.image || "assests/images/collection/thumbs/still-point.jpg") + '" alt="' + esc(item.title || order.itemSummary || "Collection artwork") + '" loading="lazy" decoding="async"><div><small>' + esc(order.orderNumber) + '</small><h3 class="order-card__title">' + esc(item.title || order.itemSummary || "Collection order") + '</h3><span class="order-status">' + esc(order.status) + '</span></div><div class="order-card__meta"><small>Date submitted</small><strong>' + esc(date(order.submittedAt, false)) + '</strong></div><div class="order-card__meta"><small>Quantity</small><strong>' + esc(order.quantity || 1) + '</strong></div><div class="order-card__meta"><small>Order total</small><strong>' + esc(money(order.grandTotal != null ? order.grandTotal : order.subtotal)) + '</strong></div><a class="order-view" href="#order=' + encodeURIComponent(order.id) + '">View Order</a></article>'; }
  function ordersView() { var content = state.orders.length ? '<div class="orders-list">' + state.orders.map(orderCard).join("") + '</div>' : '<div class="account-panel account-empty"><h3>No orders yet.</h3><p>Your collection requests will appear here after they are submitted.</p><a class="auth-button" href="collection.html" style="display:inline-block;margin-top:20px;text-decoration:none">Explore Collection</a></div>'; return heading("Collection requests", "My Orders", "Every order shown here belongs exclusively to your verified customer account.") + content; }

  function stepsFor(order) { return /collect/i.test(order.deliveryMethod || "") ? ["Confirmed", "Preparing", "Ready for Collection", "Completed"] : ["Confirmed", "Preparing", "Out for Delivery", "Completed"]; }
  function historyFor(order) { var history = Array.isArray(order.statusHistory) ? order.statusHistory.slice() : []; if (!history.length) history.push({ status: order.status || "New Request", at: order.submittedAt }); return history; }
  function tracker(order) {
    var history = historyFor(order); if (order.status === "Cancelled") { var cancelled = history.filter(function (h) { return h.status === "Cancelled"; }).pop(); return '<div class="tracker-cancelled">Order cancelled' + (cancelled ? " — " + esc(date(cancelled.at, true)) : "") + '</div>'; }
    var steps = stepsFor(order), currentIndex = steps.indexOf(order.status), pre = ["New", "New Request", "Contacted"].indexOf(order.status) > -1 ? '<p class="tracker-pre">Your request is in the <strong>' + esc(order.status) + '</strong> stage. The fulfilment timeline begins once availability is confirmed.</p>' : "";
    var markup = steps.map(function (step, index) { var event = history.filter(function (h) { return h.status === step; }).pop(); var cls = event ? "is-complete" : (index === currentIndex ? "is-current" : ""); return '<div class="tracker-step ' + cls + '"><strong>' + esc(step) + '</strong>' + (event ? '<time>' + esc(date(event.at, true)) + '</time>' : "") + '</div>'; }).join(""); return pre + '<div class="tracker">' + markup + '</div>';
  }
  function historyMarkup(order) { return '<div class="status-history">' + historyFor(order).slice().reverse().map(function (event) { return '<div class="status-history__item"><span class="status-history__dot"></span><strong>' + esc(event.status) + '</strong><time>' + esc(date(event.at, true)) + '</time></div>'; }).join("") + '</div>'; }
  function trackingView() { var current = state.orders.filter(function (o) { return o.status !== "Completed"; }); var content = current.length ? current.map(function (order) { return '<section class="account-panel" style="margin-bottom:24px"><div class="account-heading" style="margin-bottom:12px"><div><span class="account-eyebrow">' + esc(order.orderNumber) + '</span><h2 style="font-size:2.5rem">' + esc(firstItem(order).title || order.itemSummary) + '</h2></div><a class="order-view" href="#order=' + encodeURIComponent(order.id) + '">View Order</a></div>' + tracker(order) + '</section>'; }).join("") : '<div class="account-panel account-empty"><h3>No active tracking.</h3><p>Orders in progress will appear here.</p></div>'; return heading("Status updates", "Order Tracking", "Status reflects the latest stage selected by the LGNDRY.Co team. This is not live GPS tracking.") + content; }

  function orderDetail(order) { var items = Array.isArray(order.items) ? order.items : []; return '<a class="order-detail__back" href="#orders">← Back to My Orders</a>' + heading(order.orderNumber, "Order Details", "Submitted " + date(order.submittedAt, true)) + '<section class="account-panel" style="margin-bottom:28px"><span class="account-eyebrow">Current progress</span>' + tracker(order) + historyMarkup(order) + '</section><div class="order-summary-grid"><section class="account-panel"><span class="account-eyebrow">Order summary</span><div class="order-items" style="margin-top:28px">' + items.map(function (item) { return '<article class="order-item"><img src="' + esc(item.image || "") + '" alt="' + esc(item.title || "Artwork") + '" loading="lazy" decoding="async"><div><h3>' + esc(item.title || "Artwork") + '</h3><small>' + esc((item.size || "") + (item.details ? " · " + item.details : "")) + '</small><small>Quantity: ' + esc(item.quantity || 1) + '</small></div><strong>' + esc(money(item.lineTotal || Number(item.unitPrice || 0) * Number(item.quantity || 1))) + '</strong></article>'; }).join("") + '<div class="account-savebar"><span>Total</span><strong class="order-total">' + esc(money(order.grandTotal != null ? order.grandTotal : order.subtotal)) + '</strong></div></div></section><aside class="account-panel order-info"><div class="order-info__row"><span class="order-meta-label">Customer</span>' + esc(order.customerName) + '<br>' + esc(order.customerEmail) + '<br>' + esc(order.customerPhone) + '</div><div class="order-info__row"><span class="order-meta-label">Delivery</span>' + esc(order.deliveryMethod) + '<br>' + esc(order.deliveryAddress) + '<br>' + esc(order.deliveryCity) + ' ' + esc(order.postalCode) + '</div><div class="order-info__row"><span class="order-meta-label">Notes</span>' + esc(order.notes || "None") + '</div><div class="order-info__row"><span class="order-meta-label">Tracking note</span>Status updates only. Live GPS tracking is not provided.</div></aside></div>'; }

  function settingsView() { return heading("Security", "Account Settings", "Change your email address or password. Email changes require verification.") + '<div class="account-grid"><form class="account-panel auth-form" action="https://www.lgndry-co.co.za/account.html" method="post" autocomplete="on" data-email-form><span class="account-eyebrow">Email address</span><label class="auth-field"><span>New email</span><input name="email" type="email" autocomplete="email" value="' + esc(state.session.user.email) + '" required></label><p class="auth-feedback" data-email-feedback></p><button class="auth-button" type="submit">Update Email</button></form><form class="account-panel auth-form" action="https://www.lgndry-co.co.za/account.html" method="post" autocomplete="on" data-password-form><span class="account-eyebrow">Password</span><label class="auth-field"><span>New password</span><input name="password" type="password" minlength="8" autocomplete="new-password" required></label><label class="auth-field"><span>Confirm password</span><input name="confirm" type="password" minlength="8" autocomplete="new-password" required></label><p class="auth-feedback" data-password-feedback></p><button class="auth-button" type="submit">Update Password</button></form></div>';
  }

  function render() { var r = route(); setActive(r.page); if (r.page === "profile") main.innerHTML = profileView(); else if (r.page === "tracking") main.innerHTML = trackingView(); else if (r.page === "settings") main.innerHTML = settingsView(); else if (r.page === "order") { var order = state.orders.find(function (o) { return o.id === r.id; }); main.innerHTML = order ? orderDetail(order) : heading("Private order", "Order unavailable", "This order does not exist or does not belong to your account.") + '<div class="account-panel account-empty"><a class="auth-button" href="#orders" style="text-decoration:none">Return to My Orders</a></div>'; } else main.innerHTML = ordersView(); bind(); }
  function message(selector, text, ok) { var el = document.querySelector(selector); if (el) { el.textContent = text; el.classList.toggle("auth-feedback--success", !!ok); } }
  function bind() {
    var pf = document.querySelector("[data-profile-form]"); if (pf) pf.addEventListener("submit", function (e) { e.preventDefault(); var payload = { user_id: state.session.user.id, email: state.session.user.email, full_name: pf.elements.full_name.value.trim(), phone: pf.elements.phone.value.trim(), address: pf.elements.address.value.trim(), city: pf.elements.city.value.trim(), postal_code: pf.elements.postal_code.value.trim(), updated_at: new Date().toISOString() }; client.from("customer_profiles").upsert(payload).then(function (result) { if (result.error) throw result.error; state.profile = payload; return client.auth.updateUser({ data: { full_name: payload.full_name, phone: payload.phone } }); }).then(function () { message("[data-profile-feedback]", "Profile saved.", true); }).catch(function (err) { message("[data-profile-feedback]", err.message); }); });
    var ef = document.querySelector("[data-email-form]"); if (ef) ef.addEventListener("submit", function (e) { e.preventDefault(); client.auth.updateUser({ email: ef.elements.email.value.trim() }, { emailRedirectTo: location.origin + location.pathname + "#settings" }).then(function (result) { if (result.error) throw result.error; message("[data-email-feedback]", "Check both email addresses to confirm the change.", true); }).catch(function (err) { message("[data-email-feedback]", err.message); }); });
    var pw = document.querySelector("[data-password-form]"); if (pw) pw.addEventListener("submit", function (e) { e.preventDefault(); if (pw.elements.password.value !== pw.elements.confirm.value) { message("[data-password-feedback]", "Passwords do not match."); return; } client.auth.updateUser({ password: pw.elements.password.value }).then(function (result) { if (result.error) throw result.error; pw.reset(); message("[data-password-feedback]", "Password updated.", true); }).catch(function (err) { message("[data-password-feedback]", err.message); }); });
  }

  document.querySelectorAll("[data-account-logout]").forEach(function (button) { button.addEventListener("click", window.LgndryAuth.signOut); });
  document.querySelector("[data-mobile-account-nav]").addEventListener("change", function (e) { location.hash = e.target.value; });
  window.addEventListener("hashchange", render);
  window.LgndryAuth.requireSession().then(function (session) { if (!session) return; if (!session.user.email_confirmed_at) { location.replace("auth.html?mode=verify&email=" + encodeURIComponent(session.user.email || "")); return; } state.session = session; return Promise.all([client.from("customer_profiles").select("*").eq("user_id", session.user.id).maybeSingle(), client.from("orders").select("*").order("submittedAt", { ascending: false })]); }).then(function (results) { if (!results) return; if (results[0].error) throw results[0].error; if (results[1].error) throw results[1].error; state.profile = results[0].data; state.orders = results[1].data || []; render(); }).catch(function (error) { main.innerHTML = heading("Account unavailable", "We could not load your account.", error.message) + '<div class="account-panel"><p>Please refresh or contact info@lgndry-co.co.za.</p></div>'; });
}());
