(function(){
"use strict";
var root=document.querySelector("[data-showroom]");if(!root||!window.LgndrySiteData||!window.LgndryCommerce)return;
var id=new URLSearchParams(location.search).get("id"),product,products,gallery=[],index=0;
var spaces=[
{id:"living",name:"Living Room",style:"Modern Interior",image:"assests/images/curated-spaces/living-room.webp"},
{id:"hallway",name:"Hallway",style:"Scandinavian",image:"assests/images/curated-spaces/hallway.webp"},
{id:"bedroom",name:"Bedroom",style:"Minimal & Warm",image:"assests/images/curated-spaces/bedroom.webp"},
{id:"office",name:"Office",style:"Executive Suite",image:"assests/images/curated-spaces/office.webp"},
{id:"dining",name:"Dining Room",style:"Contemporary",image:"assests/images/curated-spaces/dining-room.webp"}];
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
function list(v){return String(v||"").split("\n").map(function(x){return x.trim()}).filter(Boolean)}
function normalize(p){p.artist=p.artist||"Dan Mokgwadi";p.medium=p.medium||p.seriesLabel||"Archival Pigment Print";p.collectionName=p.collectionName||(p.category==="Studio Art"?"Studio Art":"Found Beauty in the Mundane");p.deliveryEstimate=p.deliveryEstimate||"7-14 business days after payment confirmation";return p}
function reveal(){requestAnimationFrame(function(){requestAnimationFrame(function(){root.classList.add("is-ready");document.body.classList.add("showroom-loaded")})})}
function mounts(){return '<span class="curated-art" data-curated-art><span><img src="'+esc(gallery[0])+'" alt=""></span></span>'}
function card(s){return '<button class="curated-card" type="button" data-space="'+s.id+'"><span class="curated-card__scene"><img src="'+s.image+'" alt="'+s.style+' '+s.name+'" loading="lazy">'+mounts()+'<span class="curated-card__overlay">Preview Space</span></span><strong>'+s.name+'</strong><small>'+s.style+'</small></button>'}
function icon(type){var p={quality:'<rect x="5" y="3" width="14" height="18"/><rect x="8" y="6" width="8" height="12"/>',auth:'<circle cx="12" cy="9" r="6"/><path d="m8 14-1 7 5-3 5 3-1-7"/>',delivery:'<path d="M3 6h11v11H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>',edition:'<path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/>',returns:'<path d="M4 8V3m0 0h5M4 3l4 4a7 7 0 1 1-1 10"/>'};return '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.2">'+p[type]+'</svg>'}
function related(p){return '<a class="showroom-related__item" href="showroom.html?id='+encodeURIComponent(p.id)+'"><img src="'+esc(p.image)+'" alt="'+esc(p.title)+'" loading="lazy"><span>'+esc(p.title)+'</span><small>'+esc(p.artist)+' &middot; '+esc(window.LgndryCommerce.money(p.price))+'</small></a>'}
function render(){
gallery=(product.imageList&&product.imageList.length?product.imageList.slice():[product.image]).filter(Boolean);if(gallery.indexOf(product.image)<0)gallery.unshift(product.image);
var sizes=list(product.sizes||product.dimensions),presentations=list(product.framingOptions),available=product.availability==="Available"&&Number(product.remaining||0)>0;if(!sizes.length)sizes=["Standard edition"];if(!presentations.length)presentations=["Unframed"];
var rel=products.filter(function(p){return p.id!==product.id&&(p.artist===product.artist||p.collectionName===product.collectionName)}).slice(0,3),frames=["Unframed","Oak Frame","Black Frame","White Frame"];
document.title=product.title+" - LGNDRY.Co Showroom";
root.innerHTML=`<a class="showroom-back" href="collection.html">&larr; Return to the collection</a>
<section class="showroom-hero"><div class="showroom-experience"><div class="showroom-gallery">
<figure class="showroom-gallery__main" data-stage><img src="${esc(gallery[0])}" data-showroom-main alt="${esc(product.title)} by ${esc(product.artist)}"><div class="showroom-room-preview" data-room hidden><img data-room-bg alt="Curated interior"><span class="curated-art curated-art--hero" data-curated-art><span><img src="${esc(gallery[0])}" alt=""></span></span></div><button class="showroom-zoom" data-zoom type="button" aria-label="Zoom artwork">+</button></figure>
<div class="showroom-gallery__rail"><button class="gallery-arrow" data-prev type="button" aria-label="Previous view">&larr;</button><div class="showroom-gallery__thumbs">${gallery.map(function(img,i){return `<button type="button" data-image="${esc(img)}" data-index="${i}" class="${i===0?'is-active':''}"><img src="${esc(img)}" alt="Artwork view ${i+1}" loading="lazy"></button>`}).join("")}</div><button class="gallery-arrow" data-next type="button" aria-label="Next view">&rarr;</button></div></div>
<section class="curated-spaces"><div class="curated-spaces__head"><div><span class="showroom-eyebrow">In context</span><h2>Curated Spaces</h2></div><div><button data-space-prev type="button">&larr;</button><button data-space-next type="button">&rarr;</button></div></div><div class="curated-spaces__track" data-space-track>${spaces.map(card).join("")}</div></section>
<section class="showroom-trust"><div>${icon('quality')}<span><strong>Museum Quality</strong><small>Archival materials</small></span></div><div>${icon('auth')}<span><strong>Certificate of Authenticity</strong><small>Included with every work</small></span></div><div>${icon('edition')}<span><strong>Signed & Numbered</strong><small>Limited edition</small></span></div><div>${icon('delivery')}<span><strong>Secure Delivery</strong><small>Carefully packaged</small></span></div><div>${icon('returns')}<span><strong>Considered Returns</strong><small>Personal assistance</small></span></div></section></div>
<article class="showroom-details"><span class="showroom-eyebrow">${esc(product.collectionName)}</span><h1>${esc(product.title)}</h1><p class="showroom-artist">${esc(product.artist)}</p><p class="showroom-story">${esc(product.description||"An original work from the LGNDRY.Co collection, created through an attentive study of people, place, and presence.")}</p>
<dl class="showroom-specs"><div><dt>Medium</dt><dd>${esc(product.medium)}</dd></div><div><dt>Dimensions</dt><dd>${esc(product.dimensions||sizes.join(", "))}</dd></div><div><dt>Year</dt><dd>${esc(product.year||"-")}</dd></div><div><dt>Edition</dt><dd>${esc(product.editionSize?"Edition of "+product.editionSize+" - "+Number(product.remaining||0)+" available":product.seriesLabel||"Open edition")}</dd></div></dl>
<div class="showroom-purchase"><div class="showroom-price"><strong>${esc(window.LgndryCommerce.money(product.price))}</strong><span>${esc(product.availability||"Available")}</span></div><div class="showroom-options"><label class="showroom-field"><span>Size</span><select data-size>${sizes.map(function(v){return '<option>'+esc(v)+'</option>'}).join("")}</select></label><fieldset class="showroom-frames"><legend>Frame</legend><div>${frames.map(function(v,i){return '<button type="button" data-frame="'+esc(v)+'" class="'+(i===0?'is-active':'')+'">'+esc(v)+'</button>'}).join("")}</div></fieldset><label class="showroom-field"><span>Presentation</span><select data-presentation>${presentations.map(function(v){return '<option>'+esc(v)+'</option>'}).join("")}</select></label><div class="showroom-quantity"><span>Quantity</span><div><button type="button" data-minus>&minus;</button><input type="number" min="1" max="${Math.max(1,Number(product.remaining||1))}" value="1" data-quantity aria-label="Quantity"><button type="button" data-plus>+</button></div></div></div><p class="showroom-delivery">Estimated delivery: ${esc(product.deliveryEstimate)}. Delivery fees are calculated at checkout.</p><div class="showroom-actions">${available&&!product.requiresConfirmation?'<button type="button" class="showroom-primary" data-add>Add to Cart</button>':''}<button type="button" class="showroom-secondary" data-request>Send Order Request</button></div><p class="showroom-feedback" data-feedback aria-live="polite"></p></div></article></section>
${rel.length?'<section class="showroom-related"><div class="showroom-related__head"><span class="showroom-eyebrow">Continue exploring</span><h2>Related works</h2></div><div class="showroom-related__grid">'+rel.map(related).join("")+'</div></section>':''}`;
bind();sync();reveal()}
function frame(){var b=root.querySelector("[data-frame].is-active");return b?b.dataset.frame:"Unframed"}
function sync(){var s=root.querySelector("[data-size]"),scale=Math.min(.62,.38+s.selectedIndex*.07),f=frame().toLowerCase().split(" ")[0];root.querySelectorAll("[data-curated-art]").forEach(function(m){m.style.setProperty("--art-scale",scale);m.dataset.frame=f})}
function showImage(i){index=(i+gallery.length)%gallery.length;root.querySelector("[data-room]").hidden=true;root.querySelector("[data-showroom-main]").hidden=false;root.querySelector("[data-showroom-main]").src=gallery[index];root.querySelectorAll("[data-image]").forEach(function(b){b.classList.toggle("is-active",Number(b.dataset.index)===index)});root.querySelectorAll("[data-space]").forEach(function(b){b.classList.remove("is-active")})}
function showSpace(key){var s=spaces.find(function(v){return v.id===key});if(!s)return;root.querySelector("[data-showroom-main]").hidden=true;root.querySelector("[data-room]").hidden=false;root.querySelector("[data-room-bg]").src=s.image;root.querySelectorAll("[data-space]").forEach(function(b){b.classList.toggle("is-active",b.dataset.space===key)});root.querySelectorAll("[data-image]").forEach(function(b){b.classList.remove("is-active")});sync();root.querySelector("[data-stage]").scrollIntoView({behavior:"smooth",block:"center"})}
function item(){return window.LgndryCommerce.itemFromProduct(product,{size:root.querySelector("[data-size]").value,framing:frame()+" / "+root.querySelector("[data-presentation]").value,quantity:Number(root.querySelector("[data-quantity]").value||1)})}
function bind(){root.querySelectorAll("[data-image]").forEach(function(b){b.onclick=function(){showImage(Number(b.dataset.index))}});root.querySelector("[data-prev]").onclick=function(){showImage(index-1)};root.querySelector("[data-next]").onclick=function(){showImage(index+1)};root.querySelectorAll("[data-space]").forEach(function(b){b.onclick=function(){showSpace(b.dataset.space)}});var track=root.querySelector("[data-space-track]");root.querySelector("[data-space-prev]").onclick=function(){track.scrollBy({left:-360,behavior:"smooth"})};root.querySelector("[data-space-next]").onclick=function(){track.scrollBy({left:360,behavior:"smooth"})};root.querySelectorAll("[data-frame]").forEach(function(b){b.onclick=function(){root.querySelectorAll("[data-frame]").forEach(function(x){x.classList.toggle("is-active",x===b)});sync()}});root.querySelector("[data-size]").onchange=sync;var q=root.querySelector("[data-quantity]");root.querySelector("[data-minus]").onclick=function(){q.value=Math.max(1,Number(q.value)-1)};root.querySelector("[data-plus]").onclick=function(){q.value=Math.min(Number(q.max),Number(q.value)+1)};var stage=root.querySelector("[data-stage]");stage.onpointermove=function(e){var r=stage.getBoundingClientRect();stage.style.setProperty("--zx",(e.clientX-r.left)/r.width*100+"%");stage.style.setProperty("--zy",(e.clientY-r.top)/r.height*100+"%")};root.querySelector("[data-zoom]").onclick=function(){stage.classList.toggle("is-zoomed")};var add=root.querySelector("[data-add]");if(add)add.onclick=function(){window.LgndryCommerce.add(item());root.querySelector("[data-feedback]").textContent="Added to your cart.";add.textContent="Added to Cart";setTimeout(function(){add.textContent="Add to Cart"},1400)};root.querySelector("[data-request]").onclick=function(){var x=item();x.requiresConfirmation=true;window.LgndryCommerce.add(x);sessionStorage.setItem("lgndry_checkout_type","Order Request");location.href="checkout.html?type=request"}}
window.LgndryCommerce.createCartLink();window.LgndrySiteData.fetchCollection().then(function(items){products=items.map(normalize);product=products.find(function(p){return p.id===id});if(!product)throw Error();render()}).catch(function(){root.innerHTML='<div class="showroom-not-found"><span class="showroom-eyebrow">Showroom unavailable</span><h1>This artwork could not be found.</h1><a href="collection.html">Return to the collection</a></div>';reveal()})
}());
